replicaCount: 1

service:
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

image:
  name: chalky-server
  pullPolicy: Never

# This *definitely* needs changed for production.
cockroachdb:
  statefulset:
    resources:
      limits:
        memory: "500Mi"
      requests:
        memory: "250Mi"
  conf:
    cache: "125Mi"
    max-sql-memory: "250Mi"
  storage:
    persistentVolumes:
      size: "2Gi"