apiVersion: apps/v1
kind: Deployment
metadata:
  name: chalky-server-deployment
  labels:
    app: chalky-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: chalky-server
  template:
    metadata:
      labels:
        app: chalky-server
    spec:
      containers:
        - name: chalky-server-node
          image: chalky-server
          pullPolicy: Never
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PORT
              value: "{{ .Values.service.port }}"
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.service.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.service.port }}
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
