apiVersion: v1
kind: Service
metadata:
  name: chalky-server-service
spec:
  type: LoadBalancer
  selector:
    app: chalky-server
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
